apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgBFz75rFrKYaMSpBXEyEsHnsYxfbkQiX8pe2Qi+A6hUVgiwttiJLgCe2UjjouAk+SPtcfIVf0dipuZU1EceXPXXN7HmDPQhMpbouGMsOLBtwMmK4ZaYVbn0DZKdVYYBH9qSILApvQRRXfKuxh4SR9E0UWsxnRIwFLeM3hal6TPYEeZ//ddvvspTvG6t++49KAm14HFUST5pe/iRllh+D34PnVYkYjs+qnmeaUezV7SZf67cNqzXTlTuP4WgiXo3OOgvG6W/mLy5B66W+MZYhshS5fRSuF/ycGeihS9Wb5XLozviQduyoanCNF0w8hARbV4/NMWgnUS2kBdSDigCqyMJ7exUNsa2fug/RD5UR9s7UoOO63z1JT6GhS7KxXRLymaOy5ZPjR7/6s4k2JmECLvX1yFa95x+obiqqxdpaP+SC23ByAyaT9J/eOBA7VFAntV3B7xh1lx1r52emDx+BueNNaPABVbBu48mF/OidigschXI7a30JLRfvFmuRXbX6tdjUGqxWqSsBi83H58HpBTfIyWCwJSH97W8Xp2dk9gPy8LHoC0yegYxdueziQZN5Erl+wivuWzeNHHLgSeh1FWxhWPqYa+7fBMz5Rix/6NXwkQHR4e1/Wb6WKdU/rdAOQl4crS82eig0EWyG7vOxGLI1iF/9dY4VBeXQQiQ4SF3DO9JN31CvlFtaoCkDVnpvbN/XLqIfnBF60UH/vEsZITUo5HIlRqRYj0nNPU4f2nAHvRXuwhDjOIyaoGzoZHvpU/GZM1B8kcWBSTCEQKBYN9alUBh7UJDUjZ0asbJ9pfkEpWY37Qq6ZUXJXuOWWk1MPjf5Pee51rqZy3OKBu1+2XCtElBxg8=
  template:
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

