apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgAcAhjjju381bi3p5aR4SR904xj8B91yBWRubJmAkwMCBCrjvKmxmrwd90GzLITCUeI3C1TBtQwA/q++BuqQPzlslvttIWDM+ZttckvRInC4vzqswml8NTyyhOv1SOtLjImaJgMPjMvAcgyXBlk1Qm6j9Wn9muolo6V5sI5Gsw6kfjQ3BPTru6Qi/qwRw+aLnH9rRYq3/uMeXp5OXM5HaM8p5MXoiaal2jUepP6RIeBjtzWYir5t0mzhOcnkE0g8yh8nzm4+GG/9EBPSie1rtwvewCAC7peFHZ5xyO/vPAZ0SAnXlUJKgr97O1rxc1hp0rK+DL76yDBeda+l8eIIx4vU84jiS+MT8uwyZpgr34WeJ8ZAshRn003VDGfIshVubEJuaeGfWvl1hy7AK0cWn0VfYKslF58LrJquxKrmbIf8ziUzzwFsDz/kg4EmmufTbTN1/ZKi2tTH4L/rp3bGe53PE3YDCtGHrCl0MES1wwcIZ/ULuwRd9TP/P6D99jI/26bbJZZ35pZWk+F4gw/DYCaqP2CGKX6fGVND7F8I44f+jgFIGz/JAd5jplXhAWwR/maDbqBXSTc1/ZAY3FeREik/8Y5xSxUBv2gEWJw111NpLB97QNzWOPVurC7GFp6QMIzB/MjOjtBJtAA5BNxyyB2ZHmEaYV9QD+QWJxLKZ04EpvFH3r9e9OfAkEUWD8seUIaL6mvH4c5H7FqVCQU2XeT5I+ru2HDBx0XWlVfukjNNo4UO1QnRyPysEoDz7eQ8VLuIDzptaWXqfcd+5AQ9b1rx4ngi5XmmUFqvci/nKdJjYzVkFuG+kxkdgKL9yBFLHI4p/gSuOw1VopNm/LYg12+hCDpUg==
  template:
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

