apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgCqb84AEd1BGg57g+lLzUlfFBhqxaMp6r3UUFg0sPGC+5mDN3cPwmDBCW9e7jhNP/kxZli8aHN7uqmqtCzUy2p9d7pvfB0u61ivpHZqlMPsL3sXStHalqXzBMO47S9esNGmx1iiRv04Ja3XXkdONVIlnTpG2b0oqs3qAsLzwJbFQ+UPRJw6ikHfRKlbmGJ81fby5RQdTYj4lLMG05B7jGPGs7+QFXUL6Njbei5roPiNtGcIzFhbjsradNkKWFasxypynVTyV8hJqtoODTdtkHQzDRHtBrLPTVy1zjJvVbf98FmqkJAYYPg1JmtGEgoWW/wlqtuoWL7fQIhAGh4jNI34k4iZ7lGS2/SZvfn2gVWac4dnoOGkTDT1MoEw5rhHH7+ZYJp3pDoO5ThCwf1zH1ztVGBxEIhvUNP1JvznIdMR1DONz+v4Qmkw3We5SOp2qOJyf42rY1Ixbo0ASdlkfZPzClbgMIkLFX6u00wTS66lfPI+BoIo3sTkjLHFDO7XYX5LFtP07rTxBRmnplAh/YPcyVyUXUUa+KWu/qwVaKToSLU2HZ33DIaLAXqNeHIhWygDSGMvjL4GUCcena8c5lZYRDYelLnNBiW6DIpuE8gwty0KF/Hcv8z1EN4XAN0HAMaICuhyaE3LZq2JuIBrUivtmaFrlS4s8onOf2MQ6WxPcVJbRlORar8N2kjxurzvei3dNfiJqpKwCcSJc+SCGk27WFrNrYJv9BIRQu9IM8wk9rUhJIIqsOz43FMUWshjoLTTSatBrvbAnGz303UFRjjfp4DWrY+5nUdDv5iS2y2CjWCSGQg5htzTp+dAENGjfRJ3tTHq/AH1LFkg23yFB/WrKQ2mS0U=
  template:
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

