apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgAe5e2deqYjvBTDnzTmnZ0grU3abgx92smEK1kl65gtOH81q4LBUT5gXUjhEVw2rtWMNMwroLaoEmuE3HQG7b1JJcC55J+mDhTvuvpNjq8EC/0ykj2OrAZx2AL1dnaA6RcdGW1RY7a34NVAGBh8+7v2DVXQqwH8/nUzFD9T8UaCPgp6pKs3C3/fnx5qcnz8fJKbOBAVW2AvZA3H95tiZ6qhrR2IF2H75C+/xG2Khs9T5cr4E3et5vdmqeAx+1Ht95wjrURbVUTwmqGvJgyvmgsH4MfIDXpSmnwWt8SmeSZBc9EItSu8Rv+rdNs7WuriP6fsdo2DEg/BD0rNOQIXstKbQn4KSOrEBiWzC9z+ji/93R9yGzwl8p9lb/b8YAif9Th96Jne7d9DoN7QqBp1GeEDds/4or/TU9mOOBlc9waqdQybgYwfstau7IEm6055uw6B57Cd/nUlG+Og6oqBZHB8nutPvGHyFjGLBIDyLB5f9lIFwhi1yNlwHqhwXgHMAQOyBks1DwRpHoo6NEDyRu0UU7VuK3nXng+EUe/72wLf7EWvShPUmOdfMGFMnbqSVBooopJTa0qtqlfQp2EEmVHwrsce/9zRNdupnsLW2El/wIo8bYUSPUA5TUVtJ8L5/8T2QrZS5zdZ74LozKOyzwaRG/WMEYYB7Cd4WiRWc4ReiMMwyzGs5YQzkQNHbXY8RSZZnYcTqiGyFo8Afv7zE5N8x4GNY58Xs0N43AGzRRQIAA20x4ImKr9FHnG7vScrdoLFRs30VtO5sODkc1JUMDMUzVHGnyREYTL5XKhFKmLadi+zZ3FSn2Smy8joKql6q3BzKDM2ZGW5e0KarKrL9MnOWzElkg==
  template:
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

