apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgARmJ1dunZrFcYM9erEzd62CrvX4CwkRSJz0Fqki+w8eieoD2OttiVo5xNFh3p+asHf8GTudSjtP8tStnsZhptINOsayR5z/fpV3zlbwr2PwLdyR2FcMdWya20MvWTTphxlQ0o/0YjoeMsIVJ7B3lnkGjWtKRdwVaG+SoJm2mtgpUk2ph6ft2vAca71tQzgzJaP9od+RsGmGEgWRePE/s5VnADCSkxXTElrlqQjZdQc6qNU2aTgocRGJzLaKVUDmTlRLhh3aOBVsJ5qW7l2Gs3bunwgthZgYgH1N+S/M/8vcIEdOPNAqZ4y9rJTHYRZAOifRBVRTujWM3YIrAxCI2XhQ3O2NupCaFyggaYEhDqriiAJDZnp0CWWBM+OIKKtt0Ag0L5JWJ58dvUYjf3Ue4PQ3yWJgpdsQ04gKdnY+VeN+gOB/N3cAIGIyfzpz3Q5n9Psl4tyHeJ+1xa0UaoB7ZrywDmbfLHTn4ayIOZqbckyoL0Zj8LZVw0VYu+Q/nf89QPDhQxe5y5SWy41okp1ygk+BNqdbpgaK3AsLYDIl2ukHmIo9FOLcz009llzaKW6NvhDEWrhWqC80FmIXix1SdQj5Z7++ORbPZzvFay1mitS7gjeA3WplykqvdkfEXn0lFV8XkbNguUsYu7kjv8mnibH4nrcTgszc8Gq+vJrWP1EKj0tqBUPvlwurs4KqysvUUaPA+Qw8ecjKMWcE08hxC1E1to8UhZfkBg1Iv2+Qv8mMronyheK+vpSbRCLh64h1svriBTyK6N6ZJEL6YYOjlXvPWDQyCDF2mwTdVyqEIZu9utkQZtw2uEUd3ez8YYhI5TJG5I2306EV3wwg5Mh3WLw/TNZss0=
  template:
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

