apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgCjaHT8l3jFRgcaZvitLtIAuREUSgqUZHPHhzkqsJN8XpwZ0bvWbb1Z4nlFpJ6LFUiz6+ncT9BlvETJRMbq13QLtX4UZJcVc0qajT6VTt1qirzK+x3IgdLFqnA1UklMs81laYLzrlS7dtH7eDobKavmqxq2taEudgElGtm8MtEKxrLgwV9e7TLZ//sdWYro/jZPgAc9jZVXfn80E6ihWItcS65nQ2h3OKaL2mVZWsYE5SflshBgWBtbYL//3R7GqKieaLVc/X2g/cYZ+n0oPkVBgQz2E9URXc2OpHNguTJIPsnpi8eZXRL6kI5gMETlL20hAX8aKbpe7gze8rZ7lshUYYY8WrODJLfIAAVVXQAsOsKmscOyEp/9pEw+UMdlUfyL3FS7m62NMs6GsXdwUP/csgTxkA+zqCnBQxzdxpHYzqok0YBpoYJCE+s1pp1brDwZ7F0mV5uVyNl3wBHc9r0LlRQerkj7Rq8/8nOhgTUnfDC5v3Fregcted3we3X3lXNfSlPGSnmBGPPetCTOL4Ig458iBQMhMcrbX1cyT5aF8xJRZfkGiOW8Eh6i4Xzu8Oo3J4mH0AGqfsUpGdrLkuJHAw4IuXT5SS96f/S/RD8EMyqWwCPJ/b1csHaS55PRBi1pjDu2A1Sjh4Ew1nB6Mui5e+zvDlyv72fDNEGWt8gAOSKfutS2v8sW36Skll2WlKnJeTHRRkQS+4PW0zrUEBPsIOpaWmFA7WX+6cQQeDCqrgmIbr7R/GmXpcElOoOUfnSwsqALxKcLHPO4BXfILbxaDIqd2NsBOeNLqLOGiNQzAwx2ox7eOc21iH3a5j5u/2gwU+/C23fsD5fB7AQJoOeB0DWeK2w=
  template:
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

