apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: default
spec:
  encryptedData:
    foo: AgAu2E+jnENrqH/elDD7cdPTdc2oKFE26YDepZDqcqn4X4e1ltpHhNUNn3J5QtHIBoTR1ubcELse4gpne65ehLF1HCBYZAJsUWsDmplyEyXBC9rPJCvTF8X1LB6E4mVnlGH3lxRbAWy2B9H6d+Mj5o1WMopdTXaEMyxcxXT1Scvh15lpMw2XYpVS3Rat1tl3JiIiRMsaLjgsox+GrdKjygejMnAsSZVEdrRoGglCcnl78RoRViGWIyPxxWvCFvg3/YaTKgorR+WgKTrIdeNsZZmrScicPBswIkWdUf1qMsa//8Ae9KzTjW53NNbhKZodYw8De2agJfW176zcRKXqhlitfsxB2nZaZX6zB4owtBVCC0epzUSyQwIXDOUa6h4tpNA0WsxMhEuHCoVCusAKBlOxTorMv7MWEulCsLHlwKzZwyNIrwXdHE9n0fedTU0zFOR5l51EbqLIczdlYPH5QEQJNkBf4KeAbE5POBZVjj9HLA1wte5lFw5ufFaSnAkPoIl5I7rXGJgLAOXsE6gARf2CzdFqV2blfKVNDuVj8PIeU+rK5FSDx5zwlicWo/KzSM5tY8bHrgrROdNt1ts6L9g6hYvBAHD6b5e660AmgHiVyQOJJ0qeOnvr5Jx7BoxE9t7VTc6B330QSzciKr10gFLRPe1pHSKlcZKD/eVN6EjEAZYzi5L/MuWm/ywQ9vKoDhYWj4U=
  template:
    metadata:
      creationTimestamp: null
      name: mysecret
      namespace: default

